

# ?? ???? ??? ?? ? ?? ????.
spring:
  devtools:
    livereload:
      enabled: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf? ?? ??? ??? ???. cache=false ??(???? true)
    check-template-location: true  # templates ????? ??? ??? ??? ??, ??? ??? ?????.



config:
  jwt:
    secret-key: hootesttttttttttthootesttttttttttt
    payload-key: test # payload에 저장될 유저정보 키 값
    token-expire: 60  # 60초