

# ?? ???? ??? ?? ? ?? ????.
spring:
  devtools:
    livereload:
      enabled: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf? ?? ??? ??? ???. cache=false ??(???? true)
    check-template-location: true  # templates ????? ??? ??? ??? ??, ??? ??? ?????.



